//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public int IdDirector { get; set; }
        public string NombreDirector { get; set; }
        public string ContraseñaDi { get; set; }
        public string NombreUsuarioDi { get; set; }
    }
}
