//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public int IdDocente { get; set; }
        public string NombreDocente { get; set; }
        public string ContraseñaD { get; set; }
        public string NombreUsuarioD { get; set; }
        public string SexoDocente { get; set; }
    }
}
